#!/usr/bin/env python3
"""
Generate Spindle pefchain parts for the Björk koala slideshow.

For each of N koala images: a tiny contiguous effect (code at $0800) that
flips to its VIC bank, copies colour RAM to $d800, sets bg, and counts down
a per-image hold timer. Koala pixel data is placed by mkpef as positioned
data files, so the code PRG stays one page.

Double-buffer: even images -> VIC bank1 ($4000 screen / $6000 bitmap),
odd images -> VIC bank2 ($8000 screen / $a000 bitmap). pefchain preloads the
next image into the OTHER bank while the current one shows. SID is resident
via --music. Part 0 installs the play routine ('M'); later parts get their
call_play placeholder auto-patched to jsr PLAY by pefchain.

Emits src/pNN.asm, src/pNN_efo.asm, build_demo.sh, script_demo.
"""
import os, sys, json

INIT = 0x1000
PLAY = 0x1003
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEGS = json.load(open(os.path.join(ROOT, 'segments.json')))['segments']
CLIP = json.load(open(os.path.join(ROOT, 'clip.json')))
N = len(SEGS)

def bg_of(kla):
    # koala = 2 (load) + 8000 bitmap + 1000 screen + 1000 colour + 1 bg.
    # The background byte is the LAST byte (file offset 10002).
    with open(kla, 'rb') as f:
        d = f.read()
    return d[-1]

def bank_params(i):
    # Alternate BOTH the code page and the VIC bank between consecutive parts
    # so no two adjacent parts share any page -> pefchain double-buffers
    # cleanly (preloads the next image while the current shows, no fillers).
    # Spindle owns $dd00; VIC bank is selected via $dd02 (DDR): 3d=bank1
    # ($4000-7fff), 3e=bank2 ($8000-bfff). See spindle-handbook 1.3.
    if i % 2 == 0:      # bank 1, code $0800
        return dict(dd02=0x3d, code=0x0800, cpage=0x08,
                    screen=0x4000, color=0x4400, bitmap=0x6000,
                    p1=(0x40,0x47), p2=(0x60,0x7f))
    else:               # bank 2, code $0900
        return dict(dd02=0x3e, code=0x0900, cpage=0x09,
                    screen=0x8000, color=0x8400, bitmap=0xa000,
                    p1=(0x80,0x87), p2=(0xa0,0xbf))

CODE = """// p{nn}.asm — koala slideshow part {i} ({kla}).  Auto-generated by gen_parts.py.
// VIC bank {bankname}: screen ${screen:04x}, colour stage ${color:04x}, bitmap ${bitmap:04x}.
.const SCREEN = ${screen:04x}
.const COLDAT = ${color:04x}
.const BG     = ${bg}
.const HOLD   = {hold}
.const T_LO = $02      // 16-bit hold timer (loader uses pages $02/$03, NOT zp)
.const T_HI = $03
.const FLAG = $04      // advance flag, script waits FLAG==1

* = ${code:04x} "p{nn}"

setup:
{init}        lda #${dd02:02x}
        sta $dd02              // VIC bank {bankname} (Spindle owns $dd00; set bank via DDR $dd02)
        lda #$08
        sta $d018              // screen=bank+$0000, bitmap=bank+$2000
        lda #$3b
        sta $d011              // BMM=1 DEN=1 25row ysc=3
        lda #$18
        sta $d016              // MCM=1 40col
        lda #$fb
        sta $d012              // raster IRQ in lower border
        lda #BG
        sta $d021
        lda #0
        sta $d020
        lda #{sprbank}
        sta $0f
        jsr $0c09              // lyric: set sprite regs + pointers for this bank
        ldx #0
copycol:
        lda COLDAT,x
        sta $d800,x
        lda COLDAT+$100,x
        sta $d900,x
        lda COLDAT+$200,x
        sta $da00,x
        lda COLDAT+$2e8,x
        sta $dae8,x
        inx
        bne copycol
        lda #<HOLD
        sta T_LO
        lda #>HOLD
        sta T_HI
        lda #0
        sta FLAG
        jsr $0c06              // lyric: blit current line into this (freshly-flipped) bank
        rts

interrupt:
        pha
        lda $01
        pha
        lda #$35
        sta $01
        txa
        pha
        tya
        pha
{music}
        // countdown (A clobbered, X/Y preserved on stack)
        lda FLAG
        bne cdone
        lda T_LO
        bne cdec
        lda T_HI
        beq clatch
        dec T_HI
cdec:
        dec T_LO
        lda T_LO
        ora T_HI
        bne cdone
clatch:
        lda #1
        sta FLAG
cdone:
        pla
        tay
        pla
        tax
        pla
        lsr $d019
        sta $01
        pla
        rti
"""

# music block: part0 calls the resident lyric+music wrapper ($0c00) directly;
# later parts use a patched placeholder (pefchain patches -> jsr $0c00 via 'M').
MUSIC_PART0 = "        jsr $0c00               // wrapper: SID play + lyric tick"
# MUST be exactly 3 bytes: pefchain overwrites the callmusic slot with a
# 3-byte `jsr PLAY`. `bit $0000` would be optimised to a 2-byte zero-page
# BIT by KickAss, so the patch would clobber the next instruction (JAM).
# Emit the absolute-BIT opcode explicitly to lock the size at 3.
MUSIC_LATER = "call_play:\n        .byte $2c, $00, $00    // BIT $0000 placeholder; pefchain patches -> jsr PLAY"

EFO = """// p{nn}_efo.asm — EFO2 header (built -binfile, cat before p{nn}.prg).
.import source "p{nn}.sym"
.pc = $0000 "EfoHeader"
        .text "EFO2"
        .word $0000            // prepare
        .word setup
        .word interrupt
        .word $0000            // main
        .word $0000            // fadeout
        .word $0000            // cleanup
        .word {callmusic}            // callmusic
        .byte 'S'              // i/o safe
        .byte 'P', ${pc_lo:02x}, ${pc_hi:02x}    // code page(s)
        .byte 'P', ${p1a:02x}, ${p1b:02x}    // screen + colour stage
        .byte 'P', ${p2a:02x}, ${p2b:02x}    // bitmap
{sprtag}{restag}{mtag}        .byte $00
"""

def main():
    src = os.path.join(ROOT, 'src')
    os.makedirs(src, exist_ok=True)
    klas = [f"koala/img{i:02d}.kla" for i in range(N)]
    for i in range(N):
        nn = f"{i:02d}"
        bp = bank_params(i)
        bg = bg_of(os.path.join(ROOT, klas[i]))
        bankname = "1" if i % 2 == 0 else "2"
        music = MUSIC_PART0 if i == 0 else MUSIC_LATER
        hold = max(2, SEGS[i]['dur_frames'])
        sprbank = 0 if i % 2 == 0 else 1
        init = ("        lda #0\n        jsr $1000              // INIT song 0 (part 0 only)\n"
                "        jsr $0c03              // lyric: clear sprite blocks + zero clock\n"
                if i == 0 else "")
        code = CODE.format(nn=nn, i=i, kla=klas[i], bankname=bankname,
                           screen=bp['screen'], color=bp['color'],
                           bitmap=bp['bitmap'], bg=bg, hold=hold, code=bp['code'],
                           dd02=bp['dd02'], init=init, music=music, sprbank=sprbank)
        open(os.path.join(src, f"p{nn}.asm"), 'w').write(code)

        callmusic = "$0000" if i == 0 else "call_play"
        mtag = "        .byte 'M', $00, $0c    // install wrapper PLAY=$0c00\n" if i == 0 else ""
        # resident lyric engine + sprite data: part0 establishes ('P'), others inherit ('I')
        rt = 'P' if i == 0 else 'I'
        restag = (f"        .byte '{rt}', $0c, $0f    // resident lyric engine\n"
                  f"        .byte '{rt}', $31, $3f    // resident sprite shapes\n"
                  )
        sb = (0x48, 0x49) if i % 2 == 0 else (0x88, 0x89)
        sprtag = f"        .byte 'P', ${sb[0]:02x}, ${sb[1]:02x}    // sprite shape block\n"
        efo = EFO.format(nn=nn, callmusic=callmusic,
                         pc_lo=bp['cpage'], pc_hi=bp['cpage'],
                         p1a=bp['p1'][0], p1b=bp['p1'][1],
                         p2a=bp['p2'][0], p2b=bp['p2'][1], mtag=mtag,
                         restag=restag, sprtag=sprtag)
        open(os.path.join(src, f"p{nn}_efo.asm"), 'w').write(efo)

    # pefchain script. Label 0 at the top; EVERY part advances on its timer
    # (no 'stay'); pefchain --loop 0 jumps back to part0 at the end. part0's
    # setup re-INITs the SID and init_lyric (FRAME/CURSOR=0), so music, images
    # AND lyrics all restart together — a clean full-demo loop.
    lines = ["0:"]
    for i in range(N):
        lines.append(f"parts_pef/p{i:02d}.pef\t\t04 = 01")
    open(os.path.join(ROOT, 'script_demo'), 'w').write(
        "# Björk Human Behaviour koala slideshow — pefchain script.\n"
        "# Each image holds dur_frames (interrupt drains 16-bit timer -> $04=1),\n"
        "# then advances. --loop 0 restarts the whole demo (music+images+lyrics).\n"
        + "\n".join(lines) + "\n")

    # build script
    bl = ["#!/bin/bash",
          "# Auto-generated by gen_parts.py. Builds the koala slideshow d64.",
          "set -eo pipefail",
          'cd "$(dirname "$0")"',
          'KA=/home/annejan/Projects/x2026/kickass/KickAss.jar',
          'SB=/home/annejan/Projects/x2026/spindle-3.1/prebuilt-binaries/linux-x86_64',
          'PEFCHAIN="$SB/pefchain"; MKPEF="$SB/mkpef"',
          'mkdir -p parts_pef out',
          '# resident lyric engine + precomputed sprite shapes',
          'python3 tools/lyric_assets.py >/dev/null || { echo "lyric_assets FAIL"; exit 1; }',
          'java -jar "$KA" src/lyriceng.asm -o out/lyriceng.prg >/tmp/kae.log 2>&1 \\',
          '  || { echo "lyriceng build FAIL"; tail -8 /tmp/kae.log; exit 1; }',
          'tail -c +3 out/lyriceng.prg > out/lyriceng.bin',
          'for nn in ' + " ".join(f"{i:02d}" for i in range(N)) + '; do',
          '  ( cd src',
          '    java -jar "$KA" p$nn.asm -o p$nn.prg -symbolfile >/tmp/ka.log 2>&1 \\',
          '      || { echo "KA p$nn FAIL"; tail -8 /tmp/ka.log; exit 1; }',
          '    java -jar "$KA" -binfile p${nn}_efo.asm >/tmp/ka2.log 2>&1 \\',
          '      || { echo "EFO p$nn FAIL"; tail -8 /tmp/ka2.log; exit 1; }',
          '    cat p${nn}_efo.bin p$nn.prg > p$nn.efo )',
          'done']
    # per-part mkpef (bank addresses differ even/odd)
    for i in range(N):
        bp = bank_params(i)
        nn = f"{i:02d}"
        bm, sc, co = bp['bitmap'], bp['screen'], bp['color']
        data = (f"koala/img{nn}.kla,{bm:x},2,1f40 "
                f"koala/img{nn}.kla,{sc:x},1f42,3e8 "
                f"koala/img{nn}.kla,{co:x},232a,3e8")
        # resident chunk: SID + lyric engine + precomputed sprite shapes
        # (lines 0-27 at $2a00, overflow 28+ at $c000) + onset table.
        music = (f' --music {CLIP["sid"]},,7c out/lyriceng.bin,0c00 out/lyric_font.bin,3100'
                 ' out/lyric_uniq.bin,3300 out/lyric_order.bin,3b00'
                 ' out/lyric_onset.bin,3c00 out/lyric_style.bin,3e00') if i == 0 else ''
        bl.append(f'"$MKPEF" -o parts_pef/p{nn}.pef src/p{nn}.efo {data}{music}')
    bl += [
        'echo ">>> linking with pefchain"',
        f'"$PEFCHAIN" -v --title "{CLIP["title"]}" --disk-id "{CLIP["disk_id"]}" --loop 0 '
        f'-o out/{CLIP["name"]}.d64 script_demo',
        f'ls -l out/{CLIP["name"]}.d64']
    p = os.path.join(ROOT, 'build_demo.sh')
    open(p, 'w').write("\n".join(bl) + "\n")
    os.chmod(p, 0o755)
    print(f"generated {N} parts -> src/pNN.asm + src/pNN_efo.asm, "
          f"script_demo, build_demo.sh")

if __name__ == '__main__':
    main()
