// p15.asm — koala slideshow part 15 (koala/img15.kla).  Auto-generated by gen_parts.py.
// VIC bank 2: screen $8000, colour stage $8400, bitmap $a000.
.const SCREEN = $8000
.const COLDAT = $8400
.const BG     = $0
.const HOLD   = 864
.const T_LO = $02      // 16-bit hold timer (loader uses pages $02/$03, NOT zp)
.const T_HI = $03
.const FLAG = $04      // advance flag, script waits FLAG==1

* = $0900 "p15"

setup:
        lda #$3e
        sta $dd02              // VIC bank 2 (Spindle owns $dd00; set bank via DDR $dd02)
        lda #$08
        sta $d018              // screen=bank+$0000, bitmap=bank+$2000
        lda #$3b
        sta $d011              // BMM=1 DEN=1 25row ysc=3
        lda #$18
        sta $d016              // MCM=1 40col
        lda #$fb
        sta $d012              // raster IRQ in lower border
        lda #BG
        sta $d021
        lda #0
        sta $d020
        lda #1
        sta $0f
        jsr $0c09              // lyric: set sprite regs + pointers for this bank
        ldx #0
copycol:
        lda COLDAT,x
        sta $d800,x
        lda COLDAT+$100,x
        sta $d900,x
        lda COLDAT+$200,x
        sta $da00,x
        lda COLDAT+$2e8,x
        sta $dae8,x
        inx
        bne copycol
        lda #<HOLD
        sta T_LO
        lda #>HOLD
        sta T_HI
        lda #0
        sta FLAG
        jsr $0c06              // lyric: blit current line into this (freshly-flipped) bank
        rts

interrupt:
        pha
        lda $01
        pha
        lda #$35
        sta $01
        txa
        pha
        tya
        pha
call_play:
        .byte $2c, $00, $00    // BIT $0000 placeholder; pefchain patches -> jsr PLAY
        // countdown (A clobbered, X/Y preserved on stack)
        lda FLAG
        bne cdone
        lda T_LO
        bne cdec
        lda T_HI
        beq clatch
        dec T_HI
cdec:
        dec T_LO
        lda T_LO
        ora T_HI
        bne cdone
clatch:
        lda #1
        sta FLAG
cdone:
        pla
        tay
        pla
        tax
        pla
        lsr $d019
        sta $01
        pla
        rti
